### ISSUE TITLE
Document Type Template model reference

### ISSUE THREAD

**Issue by twmurph** [janvanhelvoort/qvision-poll-it#2]
I'm fairly new to Umbraco and still wrapping my head around the way it wraps MVC and auto generates classes.  I installed Poll-It, created a poll and added the picker to a document type.  Now I am trying to write the view for that document type and I'm having trouble figuring out what I should expect back from the view model.  

The only examples I see in your documentation are for a surface controller implementation.  Do you have any examples using a standard template?

**Comment by janvanhelvoort** [comment]
As far as i can see, you can use the service inside a razor view. What do you main with a standard template?

The result as view model is the json on: [link](https://github.com/janvanhelvoort/qvision-poll-it/blob/master/Documentation/developers-guide.md#result)

Can you post your view?

**Comment by twmurph** [comment]
Sorry for not being clear.  I was trying to differentiate between an Umbraco Template edited in the back office and a MVC View built in Visual Studio.  I am still trying to figure out what the class structure is that is being returned in the model or if the poll field is more appropriate way to access the poll so there isn't much in my template at this point.  What little there is I'm including below.

@inherits Umbraco.Web.Mvc.UmbracoTemplatePage<ContentModels.UmbracoPoll>
@using ContentModels = Umbraco.Web.PublishedContentModels;
@{
	Layout = null;
	
	var question = Umbraco.Field("poll");
	var questionName = Model.poll;
	//var questionName = question.Name.ToString();
}

<p>This is a poll</p>
<p>@questionName</p>

**Comment by janvanhelvoort** [comment]
homePage.cshtml (Template) - where `Model.Poll` is the model property (Alias: poll)

```
@inherits UmbracoViewPage<Qvision.Umbraco.PollIt.Website.Models.ContentModels.Home>
@Html.Partial("~/views/partials/poll.cshtml", Model.Poll)
```

partial poll.cshtml
```
@inherits UmbracoViewPage<Qvision.Umbraco.PollIt.Models.Question>
<p>@Model.Name</p>
<ul>
    @using (Html.BeginUmbracoForm("Post", "PollSurface"))
    {
        @Html.Hidden("questionId", Model.Id)

        foreach (var answer in Model.Answers)
        {
            <li>
                @Html.RadioButton("answerId", answer.Id, false)
                @answer.Percentage% - @answer.Value
            </li>
        }

        <button type="submit">post</button>
    }
</ul>
```

PollSurfaceController.cs - add a vote, used by the view above. This returns the same view, with updated data
```
public class PollSurfaceController : SurfaceController
{
    public ActionResult Post([FromBody] int questionId, [FromBody] int answerId)
    {            
        return this.View("partials/poll", PollItService.Current.Vote(questionId, answerId));
    }
}
```

Hope this will help you!

**Comment by twmurph** [comment]
I tried updating the "inherits" directive to use the Home content model, but I get the following error.

_The type or namespace name 'Website' does not exist in the namespace 'Qvision.Umbraco.PollIt' (are you missing an assembly reference?)_

I looked at the PollIt assembly reference and it confirms that the Website namespace does not exist.  I installed PollIt via the Packages library in the Developer section of the back office.  Are there additional steps that are not documented?   The version of the assembly in my references is 0.5.0.20670

**Comment by janvanhelvoort** [comment]
this namespace: `Qvision.Umbraco.PollIt.Website.Models.ContentModels.Home` is from a project of me. You need to change this to the namespace / model of your template.

`Qvision.Umbraco.PollIt.Website` need to change in yours project namespace

**Comment by janvanhelvoort** [comment]
@twmurph do you still have any questions?

**Comment by twmurph** [comment]
Sorry, I had to put aside working on this and I'm just getting back to it.  I'm working on building the surface controller right now and looking at the PollItService.  I am not finding that in my project and wondering if there is a step missing in the documentation or if that only installs from the NuGet package instead of with the Umbraco package.

Since I previously installed the Umbraco package I am now installing the NuGet package to see if I can get further with setting up the controller.

**Comment by twmurph** [comment]
I managed to get the basic view and voting working once I started using the NuGet package instead of the package loaded from the developer tab of the Umbraco back office.

I hate to add a question inside another, but I don't want to open a new issue you have to track.  I don't see a way to track is a user has answered a question.  Am I missing something?

**Comment by janvanhelvoort** [comment]
I think, after installation within umbraco as a package instead of NuGet, you need to add a reference to te .dll inside the bin folder. 

For your second question, you didn't miss something. But you need to track them your self, with a cookie or something. I didn't want to store ip addresses or something within Umbraco and because it is only a custom section with services, i can't place cookies. When a user vote, u can place the cookie.
