### ISSUE TITLE
Section not visible

### ISSUE THREAD

**Issue by twmurph** [janvanhelvoort/qvision-poll-it#3]
I have Poll-it working locally, but when we tried to migrate it to another developer's machine or to our development server the Poll-It section does not show up in the back office.  I installed the NuGet package in the project and we have tried also installing the package from the developer tab.

Since I started development the version on the Umbraco package list has been updated from 0.5.0 to 0.7.0.  I tried manually installing the earlier version using the local install feature on the dev server since I don't want to risk braking working code on my local machine.

Can you point me in the direction of what might be preventing us from getting this installed correctly?

**Comment by twmurph** [comment]
This was a permissions issue. I am closing the issue.

**Comment by janvanhelvoort** [comment]
With Umbraco 7.7, the sections aren't managed at user level, but with user groups. The possibility to easily add a new section to a group isn't available at the moment.
