### ISSUE TITLE
Poll-It section does not show up

### ISSUE THREAD

**Issue by ctf1** [janvanhelvoort/qvision-poll-it#4]
Poll-It section does not show up in the back office. I installed the package inside umbraco > developer tab > packages
I tried to see if it's permissions but i don't see anything to add or change, i am the admin on the box and i also tried creating a user and don't see anything on that user.

kinda a newbie, so it''s might be something im doing, but i tried version 7.7 and 7.8 beta.

**Comment by janvanhelvoort** [comment]
With Umbraco 7.7, the sections aren't managed at user level, but with user groups. The possibility to easily add a new section to a group isn't available at the moment, as you can read #3 

Now you need to go to users, select group at the upper right corner and than add the section to the user group of your needs.
